{{ $args := dict "namespace" .Values.kuadrant.namespace "subscription" "kuadrant-operator" "catalogsource" "kuadrant-upstream" "catalogsourceNamespace" .Values.kuadrant.namespace }}
{{ include "operators.catalogsource-wait" $args }}