kuadrant:
  # Namespace where kuadrant operator will be installed
  # If set to 'openshift-operators' it will be installed to this default Openshift namespace for operators.
  namespace: kuadrant-system

  # OLM index image to use for kuadrant deployment, creates CatalogSource CR with this image
  # If left empty it uses CatalogSource defined in catalogSource
  # For list of available upstream CatalogSource's see https://quay.io/repository/kuadrant/kuadrant-operator-catalog?tab=tags
  indexImage: 'quay.io/kuadrant/kuadrant-operator-catalog:v1.3.0'

  # (optional)
  # Name of pull secret for pulling indexImage if needed. Can be left empty.
  pullSecret: ""

  # 'kuadrant-operator' if installing upstream
  # 'rhcl-operator' if installing downstream
  # 'authorino-operator' if installing Authorino standalone
  operatorName: kuadrant-operator

  # 'preview' for nightly builds, release candidates and builds from Pull requests
  # 'stable' for released builds
  channel: stable

  # (optional)
  # redhat-operators for downstream
  # or
  # name of a custom CatalogSource. Be sure to set catalogSourceNamespace as well
  catalogSource: "redhat-operators"

  # (optional)
  # "openshift-marketplace" is the default namespace for CatalogSources
  catalogSourceNamespace: "openshift-marketplace"

  # (optional)
  # If installation of a lower than the newest version is required, set this to 'Manual' and set startingCSV
  installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

  # (optional)
  # When installPlanApproval is set to 'Manual' this exact version will be installed
  # Examples:
  # rhcl-operator.v1.1.0
  # kuadrant-operator.v0.0.0 = nightlies
  # kuadrant-operator.v1.2.0
  startingCSV: "kuadrant-operator.v0.0.0"

  # (optional)
  # If specified, these will be used as values for RELATED_IMAGE_WASMSHIM and PROTECTED_REGISTRY env vars respectively.
  # Example values would be
  # "registry.stage.redhat.io/rhcl-1/wasm-shim-rhel9@sha256:c78019c49f4f2d03da9df6e2711585333a7b4a409011d105bdaab3b391ef7670"
  # and
  # "registry.stage.redhat.io"
  # respectively.
  # If protected registry is not used leave the protectedRegistry empty.
  # If protected registry is used the protectedRegistry value must be the same as a registry of wasmPluginImage.
  # IMPORTANT: When using protectedRegistry, ensure that a pull secret named
  # 'wasm-plugin-pull-secret' exists in the Gateway namespace before deployment.
  wasmPluginImage: ""
  protectedRegistry: ""

  # Enable debug and observability for Kuadrant and its components
  enableDebug: true

# Installs Gateway API CRD's on cluster. Not needed for Openshift 4.19+
gatewayAPI:
  version: v1.4.0  # v1.2.1, v1.3.0, v1.4.0 available; leave empty for installing on Openshift 4.19+

# Gateway API implementation. Currently only Openshift Service Mesh 3 is supported
istio:
  namespace: istio-system
  cniNamespace: istio-cni
  operatorNamespace: istio-system-operator
  # 'ossm3' for Openshift Service mesh v3 (recommended for every Openshift versions)
  # 'ocp' for installing Istio managed by Gateway API (not recommended: mTLS is not supported)
  # if left empty no Gateway API implementation is installed
  istioProvider: ossm3
  ossm3:  # Openshift Service Mesh, but version 3
    version: v1.26-latest
    operator:
      channel: stable
      startingCSV: servicemeshoperator3.v3.0.0  # Ignored if 'Automatic' bellow
      installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

# Kuadrant operator dependency
certManager:
  operator:
    channel: stable-v1
    startingCSV: cert-manager-operator.v1.15.0  # Ignored if 'Automatic' bellow
    installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

# Optional objects used for Kuadrant testing
# Note: For setting tools values go to values-tools.yaml
tools:
  enabled: "false"  # if 'true' the testing environment will be set up

# OpenTelemetry tracing configuration for Kuadrant operator
# When enabled, the operator will export traces to Jaeger using OTLP protocol)
# The operator will be configured with the following OTEL environment variables:
#   - OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.tools.svc.cluster.local:4318"
#   - OTEL_EXPORTER_OTLP_INSECURE: "true"
enableTracing:
  enable: true

additionalManifests: []

preOperatorInstallManifests: []
