kuadrant:
  # Namespace where kuadrant operator will be installed
  # If set to 'openshift-operators' it will be installed to this default Openshift namespace for operators.
  namespace: kuadrant-system

  # OLM index image to use for kuadrant deployment, creates CatalogSource CR with this image
  # If left empty it uses CatalogSource defined in catalogSource
  # For list of available upstream CatalogSource's see https://quay.io/repository/kuadrant/kuadrant-operator-catalog?tab=tags
  indexImage: 'quay.io/kuadrant/kuadrant-operator-catalog:v1.2.0'

  # (optional)
  # Name of pull secret for pulling indexImage if needed. Can be left empty.
  pullSecret: ""

  # 'kuadrant-operator' if installing upstream
  # 'rhcl-operator' if installing downstream
  operatorName: kuadrant-operator

  # 'preview' for nightly builds, release candidates and builds from Pull requests
  # 'stable' for released builds
  channel: stable

  # (optional)
  # redhat-operators for downstream
  # or
  # name of a custom CatalogSource. Be sure to set catalogSourceNamespace as well
  catalogSource: "redhat-operators"

  # (optional)
  # "openshift-marketplace" is the default namespace for CatalogSources
  catalogSourceNamespace: "openshift-marketplace"

  # (optional)
  # If installation of a lower than the newest version is required, set this to 'Manual' and set startingCSV
  installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

  # (optional)
  # When installPlanApproval is set to 'Manual' this exact version will be installed
  # Examples:
  # rhcl-operator.v1.1.0
  # kuadrant-operator.v0.0.0 = nightlies
  # kuadrant-operator.v1.2.0
  startingCSV: "kuadrant-operator.v0.0.0"

  # (optional)
  # If specified it will be used as a value for RELATED_IMAGE_WASMSHIM env var
  # Examples:
  # registry.redhat.io/rhcl-1/wasm-shim-rhel9@sha256:845bb8af57f3d219aa09b9c0bb20fa945306f3b413e34e196760c8cdf624a532
  # oci://quay.io/kuadrant/wasm-shim:9f114d4c725e4b81eab38306bace96547db18f71
  wasmPluginImage: ""

# Installs Gateway API CRD's on cluster. Not needed for Openshift 4.19+
gatewayAPI:
  version: v1.3.0  # v1.0.0, v1.1.0, v1.2.1, v1.3.0 available; empty value will not create any CRD

# Gateway API implementation. Currently only Openshift Service Mesh 3 is supported
istio:
  namespace: istio-system
  cniNamespace: istio-cni
  operatorNamespace: istio-system-operator
  # 'ossm3' for Openshift Service mesh v3
  # 'ocp' for installing on Openshift 4.19+
  # if left empty no Gateway API implementation is installed
  istioProvider: ossm3
  ossm3: # Openshift Service Mesh, but version 3
    version: v1.24-latest
    operator:
      channel: stable
      startingCSV: servicemeshoperator3.v3.0.0  # Ignored if 'Automatic' bellow
      installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

# Kuadrant operator dependency
certManager:
  operator:
    channel: stable-v1
    startingCSV: cert-manager-operator.v1.15.0 # Ignored if 'Automatic' bellow
    installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'

# Optional objects used for Kuadrant testing
# Note: For setting tools values go to tools/values.yaml
tools:
  enabled: "false"  # if 'true' the testing environment will be set up

additionalManifests: []
