tools:
  namespace: tools
  jaeger:
    enable: true
    image: quay.io/jaegertracing/jaeger
  mockserver:
    enable: true
    image: quay.io/rhn_support_azgabur/mockserver:latest
  keycloak:
    enable: true
    # 'operator' for RHBK operator
    # 'deployment' for Keycloak deployment
    keycloakProvider: "operator"
    operator:
      channel: stable-v26
      startingCSV: rhbk-operator.v26.0.10-opr.1  # Ignored if 'Automatic' bellow
      installPlanApproval: Automatic  # can be 'Automatic' or 'Manual'
    deployment:
      image: quay.io/keycloak/keycloak:26.4
    database:
      image: registry.redhat.io/rhel9/postgresql-16
  redis:
    enable: true
    image: quay.io/opstree/redis:latest
  dragonfly:
    enable: true
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
  valkey:
    enable: true
    image: ghcr.io/valkey-io/valkey:latest
  customMetricsApiserver:
    enable: true
    image: quay.io/acristur/custom-metrics-apiserver:latest
  coredns:
    enable: false
    metrics: false
    zone: "k.example.com"
    image: quay.io/kuadrant/coredns-kuadrant:latest
