{{if ne .Values.kuadrant.operatorName "authorino-operator"}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: {{ .Values.certManager.operator.channel }}
  installPlanApproval: {{ .Values.certManager.operator.installPlanApproval }}
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  {{if eq .Values.certManager.operator.installPlanApproval "Manual"}}
  startingCSV: {{ .Values.certManager.operator.startingCSV}}
  {{end}}
{{end}}
