{{ if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.kuadrant.operatorName "authorino-operator") (eq .Values.kuadrant.enableObservability true) }}
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default-telemetry
  namespace: {{ .Values.istio.namespace }}
spec:
  tracing:
    - providers:
        - name: jaeger-otlp
      randomSamplingPercentage: 100
  {{ end }}