{{ if .Values.tools.jaeger.enable }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Values.tools.namespace }}
  labels:
    jaeger-infra: collector-service
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      appProtocol: grpc
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    jaeger-infra: jaeger-pod
  type: ClusterIP
{{end}}
